# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  dotNetCoreVersion: '3.1.x'
  major: 1
  minor: 0
  build: 0
  revision: $[counter('rev', 0)]

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.3.0'
    checkLatest: true

- task: UseDotNet@2
  displayName: 'Use dotNet $(dotNetCoreVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotNetCoreVersion)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
   [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq") | Out-Null
   $path = "$(System.DefaultWorkingDirectory)/StreamSubtitles.Package/Package.appxmanifest"
   $doc = [System.Xml.Linq.XDocument]::Load($path)
   $xName = "{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity"
   $doc.Root.Element($xName).Attribute("Version").Value = "$(major).$(minor).$(build).$(revision)";
   $doc.Save($path)
  displayName: 'Version Package Manifest'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxPackageSigningEnabled=false'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: MSBuild@1
#  inputs:
#    solution: '**/StreamSubtitles.Package.wapproj'
#    platform: $(buildPlatform)
#    configuration: $(buildConfiguration)
#    msbuildArguments: '/p:OutputPath=NonPackagedApp /p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxPackageSigningEnabled=false'
#  displayName: 'Package the App'

# - task: DownloadSecureFile@1
#   inputs:
#     secureFile: 'certificate.pfx'
#   displayName: 'Download Secure PFX File'

# - script: 'signtool sign /fd SHA256 /f $(Agent.TempDirectory)/certificate.pfx /p $(certPassword) $(Build.ArtifactStagingDirectory)/MsixDesktopApp.msix'
#   displayName: 'Sign MSIX Package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'